---
- name: Snap refresh
  become: true
  ansible.builtin.command: snap refresh
  changed_when: false

- name: Install Snapd
  become: true
  community.general.snap:
    name: snapd

- name: Install Snap core
  become: true
  community.general.snap:
    name: core

- name: Add /snap/bin to PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: export PATH=$PATH:/snap/bin
    regexp: '^export PATH=.*:/snap/bin$'
