---
- name: Remmina - snap install
  become: true
  community.general.snap:
    name: remmina

- name: Remmina - snap fixes
  become: true
  ansible.builtin.command: "{{ item }}"
  changed_when: false
  loop:
    - snap connect remmina:avahi-observe :avahi-observe
    - snap connect remmina:cups-control :cups-control
    - snap connect remmina:mount-observe :mount-observe
    - snap connect remmina:password-manager-service :password-manager-service
    - snap connect remmina:audio-playback :audio-playback
    - snap connect remmina:audio-record :audio-record
