---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: '{{ sdkman_dependencies }}'
    state: present

- name: Install SDKMAN via official installer
  become: true
  become_user: "{{ item }}"
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://get.sdkman.io | bash
  args:
    executable: /bin/bash
    creates: "~{{ item }}/.sdkman/bin/sdkman-init.sh"
  loop: "{{ sdkman_users }}"

- name: Install .sdkmanshrc
  become: true
  become_user: '{{ item }}'
  ansible.builtin.template:
    src: 'sdkmanshrc.j2'
    dest: '~/.sdkmanshrc'
    mode: 'u=rw,go=r'
  loop: '{{ sdkman_users }}'

- name: Configure .bashrc
  become: true
  become_user: '{{ item }}'
  ansible.builtin.lineinfile:
    path: '~/.bashrc'
    state: present
    regexp: '^source ~/.sdkmanshrc'
    line: 'source ~/.sdkmanshrc #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!'
    create: true
    mode: 'u=rw,go=r'
  loop: '{{ sdkman_users }}'

- name: Configure .zshrc
  become: true
  become_user: '{{ item }}'
  ansible.builtin.lineinfile:
    path: '~/.zshrc'
    state: present
    regexp: '^source ~/.sdkmanshrc'
    line: 'source ~/.sdkmanshrc #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!'
    create: true
    mode: 'u=rw,go=r'
  loop: '{{ sdkman_users }}'
