---
- name: Detect Linux variables
  ansible.builtin.import_tasks: linux_vars.yml
  when: ansible_os_family != "Darwin"

- name: Assert home directory is detected
  ansible.builtin.assert:
    that: user_home | length > 0

- name: Assert current shell is detected
  ansible.builtin.assert:
    that: user_shell | length > 0

- name: Clone bash_it for {{ user }}
  become: true
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ repository }}"
    dest: "{{ user_home }}/.bash_it"
    version: "{{ version }}"

- name: .bash_profile loads .bashrc for {{ user }}
  ansible.builtin.blockinfile:
    dest: "{{ user_home }}/.bash_profile"
    create: true
    owner: "{{ user }}"
    mode: '0644'
    block: |
      if [ -f ~/.bashrc ]; then
        source ~/.bashrc
      fi

- name: Change shell to bash for {{ user }}
  become: true
  become_user: root
  ansible.builtin.command: "chsh -s /bin/bash {{ user }}"
  when: user_shell != "/bin/bash"
  changed_when: true

- name: Install bash_it on .bashrc for {{ user }}
  ansible.builtin.lineinfile:
    dest: "{{ user_home }}/.bashrc"
    create: true
    owner: "{{ user }}"
    mode: '0644'
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^export BASH_IT=', line: 'export BASH_IT="$HOME/.bash_it"' }
    - { regexp: '^export BASH_IT_THEME=', line: 'export BASH_IT_THEME={{ theme }}' }
    - { regexp: '^source \$BASH_IT', line: 'source $BASH_IT/bash_it.sh' }

- name: Install bash_it plugins for {{ user }}
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "/bin/bash -i -l -c \"bash-it enable plugin {{ plugins | join(' ') }}\""
  when: plugins is defined
  register: plugins_result
  changed_when: "plugins_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"

- name: Install bash_it aliases for {{ user }}
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "/bin/bash -i -l -c \"bash-it enable alias {{ aliases | join(' ') }}\""
  when: aliases is defined
  register: aliases_result
  changed_when: "aliases_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"

- name: Install bash_it completions for {{ user }}
  become: true
  become_user: "{{ user }}"
  ansible.builtin.command: "/bin/bash -i -l -c \"bash-it enable completion {{ completions | join(' ') }}\""
  when: completions is defined
  register: completions_result
  changed_when: "completions_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"

- name: Add environment variables to .bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: "export EDITOR=vim"
    regexp: '^export EDITOR='

- name: Copy Bash-It custom aliases into place
  ansible.builtin.copy:
    src: custom.aliases.bash
    dest: "~/.bash_it/aliases/"
    mode: '0644'
