- name: Install Core tools
  hosts: localhost
  connection: local

  tasks:

    - name: Disable auto-upgrade timer
      become: yes
      command:
        cmd: systemctl disable {{ item }}.timer
        removes: /etc/systemd/system/timers.target.wants/{{ item }}.timer
      loop:
        - apt-daily
        - apt-daily-upgrade

    - name: Create /etc/apt/keyrings
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Add ~/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:~/bin

    - name: Enable HTTPS APT support
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Upgrade to latest APT packages
      become: yes
      apt:
        upgrade: yes

    - name: Install core packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - curl
        - dconf-editor
        - exfat-fuse
        - htop
        - inetutils-traceroute
        - jq
        - net-tools
        - p7zip-full
        - unzip
        - uuid
        - xclip
        - vim
        - htop
        - iftop
        - net-tools
        - cheat

    - name: Get installed package list
      package_facts: {}

    - name: Add dm-crypt to /etc/initramfs-tools/modules
      become: yes
      lineinfile:
        path: /etc/initramfs-tools/modules
        line: dm-crypt
      when: ansible_facts.packages["cryptsetup-initramfs"] is defined

    - name: Ensure ~/.hushlogin exists
      file:
        path: ~/.hushlogin
        state: touch
