---
- name: Install Node Version Manager (nvm)  # noqa: command-instead-of-module
  become: false
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Test for installed NodeJS LTS
  ansible.builtin.shell: bash -ic "nvm ls lts/*" >/dev/null
  register: nvm_ls
  failed_when: false
  changed_when: false

- name: Install NodeJS LTS
  ansible.builtin.command: bash -ic "nvm install lts/*"
  when: nvm_ls.rc != 0
  changed_when: true

- name: Use NodeJS LTS by default
  ansible.builtin.command: bash -ic "nvm use --lts"
  when: nvm_ls.rc != 0
  changed_when: true
