---
- name: Install Node Version Manager (nvm)
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"

- name: Test for installed NodeJS LTS
  shell: bash -ic "nvm ls lts/*" >/dev/null
  register: nvm_ls
  ignore_errors: yes
  changed_when: false

- name: Install NodeJS LTS
  command: bash -ic "nvm install lts/*"
  when: nvm_ls.failed

- name: Use NodeJS LTS by default
  command: bash -ic "nvm use --lts"
  when: nvm_ls.failed
