---
- name: Enpass - repository key exists?
  become: true
  ansible.builtin.apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: Enpass - APT repository exists?
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://apt.enpass.io/ stable main"
    state: present
    filename: enpass

- name: Enpass - install
  become: true
  ansible.builtin.apt:
    name: enpass
    state: present
    update_cache: true
