---
- name: Detect WSL
  ansible.builtin.set_fact:
    is_wsl: "{{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}"

- name: Test for hypervisor
  ansible.builtin.shell: dmesg | grep -i "hypervisor detected" || true
  register: hypervisor
  changed_when: false
  when: not is_wsl

- name: Install QEMU/KVM
  become: true
  ansible.builtin.apt:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - ovmf
      - qemu-kvm
      - virt-manager
  when: not is_wsl and hypervisor.stdout == ""

- name: Enable QEMU/KVM for current user
  become: true
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
    append: true
  when: not is_wsl and hypervisor.stdout == ""
