- name: Install Node Version Manager (NVM)
  hosts: localhost
  tasks:
    - name: Install Node Version Manager (nvm)
      become: no
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
